IMAGE_INSTALL:append:qemuall = " \
    ptest-runner \
    \
    python3-accuweather-ptest \
    python3-aiodiscover-ptest \
    python3-aiohasupervisor-ptest \
    python3-aioshelly-ptest \
    python3-airthings-ble-ptest \
    python3-bleak-retry-connector-ptest \
    python3-bluetooth-adapters-ptest \
    python3-bluetooth-auto-recovery-ptest \
    python3-evohome-async-ptest \
    python3-home-assistant-bluetooth-ptest \
    python3-homeassistant-ptest \
    python3-psutil-home-assistant-ptest \
    python3-s3transfer-ptest \
    python3-uart-devices-ptest \
    python3-usb-devices-ptest \
"
