IMAGE_INSTALL += "\
    ptest-runner \
    \
    python3-aiodiscover-ptest \
    python3-aiohttp-isal-ptest \
    python3-bleak-retry-connector-ptest \
    python3-bluetooth-adapters-ptest \
    python3-bluetooth-auto-recovery-ptest \
    python3-uart-devices-ptest \
    python3-usb-devices-ptest \
    \
    python3-home-assistant-bluetooth-ptest \
    python3-psutil-home-assistant-ptest \
    \
    python3-homeassistant-ptest \
"

# IMAGE_FEATURES += "\
#     ptest-pkgs \
# "
