name: Gitea Actions Sanctum Project
run-name: ${{ gitea.actor }} is building the sanctum project
on: [push]

jobs:
  Build-Core-Image-HomeAssistant-QemuArm64-A72:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build QemuArm64-A72 Core Image Homeassistant
        run: |
          TEMPLATECONF=${{ gitea.workspace }}//conf/templates/sanctum . ${{ gitea.workspace }}/sources/poky/oe-init-build-env
          MACHINE=qemuarm64-a72 bitbake core-image-homeassistant-full
