name: Gitea Actions Sanctum Project
run-name: ${{ gitea.actor }} is building the sanctum project
on: 
  push:
  schedule:
    - cron: '@weekly'

jobs:
  Build-Core-Image-HomeAssistant-QemuArm64-A72:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build QemuArm64-A72 Core Image Homeassistant
        run: |
          kas build kas/home-assistant-test-kas.yml

  Clean-Up-Cache:
    runs-on: yocto-builder
    container:
      volumes:
        - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Clean SState Cache
        run: |
          kas checkout kas/home-assistant-test-kas.yml
          python3 ${{ gitea.workspace }}/sources/poky/scripts/sstate-cache-management.py --cache-dir=/cache/sstate -y -d -v