name: Gitea Actions Sanctum Project
run-name: ${{ gitea.actor }} is building the sanctum project
on: 
  push:
  schedule:
    - cron: '@weekly'

jobs:
  Build-Core-Image-HomeAssistant-QemuArm64-A72:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build QemuArm64-A72 Core Image Homeassistant
        run: |
          kas build kas/home-assistant-test-kas.yml
      - name: Send failure mail
        if: failure()
        uses: https://github.com/dawidd6/action-send-mail@v3
        with:
          to: ${{ secrets.MAIL_TO }}
          from: Gitea <gitea@hostname>
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: ${{ gitea.repository }} ${{gitea.workflow}} ${{ job.status }}
          priority: high
          attachments: build/tmp/work/qemuarm64_a72-oe-linux/core-image-homeassistant-full/1.0/temp/log.do_testimage.*
          convert_markdown: true
          html_body: |
              ### Job ${{ job.status }}

              ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)
      - name: Send success mail
        if: failure()
        uses: https://github.com/dawidd6/action-send-mail@v3
        with:
          to: ${{ secrets.MAIL_TO }}
          from: Gitea <gitea@hostname>
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: ${{ gitea.repository }} ${{gitea.workflow}} ${{ job.status }}
          priority: high
          convert_markdown: true
          html_body: |
              ### Job ${{ job.status }}

              ${{ github.repository }}: [${{ github.ref }}@${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/actions)

  Clean-Up-Cache:
    runs-on: yocto-builder
    container:
      volumes:
        - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Clean SState Cache
        run: |
          kas checkout kas/home-assistant-test-kas.yml
          python3 ${{ gitea.workspace }}/sources/poky/scripts/sstate-cache-management.py --cache-dir=/cache/sstate -y -d -v