name: Gitea Container Actions
run-name: ${{ gitea.actor }} is building the sanctum project containers
on: 
  schedule:
    - cron: '@weekly'

jobs:
  Build-Container:
    runs-on: ubuntu-latest
    container:
          image: catthehacker/ubuntu:act-latest
    env: 
        RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            [registry."${{ secrets.DOMAIN_NAME }}"]
              http = true
              insecure = true 
      - name: Log in to Docker registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOMAIN_NAME }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: utils/dockerfile
          push: true
          tags: "${{ secrets.DOMAIN_NAME }}/${{ secrets.USER }}/yocto-builder:latest"
      - name: Send failure mail
        if: failure()
        uses: https://github.com/dawidd6/action-send-mail@v6
        with:
          to: ${{ secrets.MAIL_TO }}
          from: Gitea <gitea@hostname>
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: Docker Container Build Failed
          priority: high
          convert_markdown: true
          html_body: |
              ### Job Container Creation ${{ job.status }}
