name: Gitea HomeAssistant Actions Sanctum Project
run-name: ${{ gitea.actor }} is building the sanctum project
on: 
  push:
  schedule:
    - cron: '@weekly'

jobs:
  Stable:
    runs-on: yocto-builder
    env: 
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    container:
      volumes:
          - /cache/:/cache/
          - /dev/kvm:/dev/kvm/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build QemuX86-64 Core Image Homeassistant
        run: |
          kas build kas/homeassistant/ptest-x86-home-assistant-kas.yml
      - name: Send failure mail
        if: failure()
        uses: https://github.com/dawidd6/action-send-mail@v3
        with:
          to: ${{ secrets.MAIL_TO }}
          from: Gitea <gitea@hostname>
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: Meta Sanctum - Home Assistant Stable Core Failed
          priority: high
          convert_markdown: true
          html_body: |
              ### Job QemuX86-64 Core Image Homeassistant Stable ${{ job.status }}
