name: Gitea Actions Sanctum Project
run-name: ${{ gitea.actor }} is building the sanctum project
on: 
  push:
  schedule:
    - cron: '@weekly'

jobs:
  QemuArm64:
    runs-on: yocto-builder
    env: 
      RUNNER_TOOL_CACHE: /toolcache # Runner Tool Cache
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build QemuArm64
        run: |
          kas build kas/qemu/arm64-qemu-kas.yml
      - name: Run RAUC update test
        run: |
          ./tests/rauc-test.sh qemuarm64-a72
      - name: Send failure mail
        if: failure()
        uses: https://github.com/dawidd6/action-send-mail@v3
        with:
          to: ${{ secrets.MAIL_TO }}
          from: Gitea <gitea@hostname>
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.OUTLOOK_EMAIL }}
          password: ${{ secrets.OUTLOOK_PASSWORD }}
          subject: Meta Sanctum - QemuArm64 - Status = ${{ job.status }}
          priority: high
          convert_markdown: true
          html_body: |
            ### Job Qemu - Arm64 Image ${{ job.status }}

            The build step failed with the following output:

            ```
            ${{ steps.Build_QemuX86_64.outputs.stdout }}
            ${{ steps.Build_QemuX86_64.outputs.stderr }}
            ```
