#@TYPE: Machine
#@NAME: QEMU ARMv8 machine based on A72 tuning 
#@DESCRIPTION: Machine configuration for running an ARMv8 system on QEMU

MACHINEOVERRIDES = "qemuarm64:${MACHINE}"

require conf/machine/qemuarm64.conf

KMACHINE = "qemuarm64"

SERIAL_CONSOLES = "115200;ttyAMA0"
QB_KERNEL_CMDLINE_APPEND = "swiotlb=0 earlycon=pl011,0x9000000 ignore_loglevel loglevel=8"

WKS_FILE = "qemuarm64-a72.wks.in"
IMAGE_BOOT_FILES = "\
    u-boot.bin \
    boot.scr \
    fitImage \
"

do_image_wic[depends] += " \
    sanctum-bootfs:do_image_complete \
"

UBOOT_EXTLINUX = "0"
KERNEL_BOOTCMD = "bootm"

# Set bootloader file
QB_DEFAULT_BIOS = "u-boot.bin"
QB_FSINFO = "wic:no-kernel-in-fs"
QB_DEFAULT_FSTYPE = "wic"

IMAGE_FSTYPES:append = " \
    wic \
    wic.bmap \
"
