FROM catthehacker/ubuntu:act-22.04

# Set environment variables for locale
ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

# Install all yocto dependencies
RUN apt update && apt install -y \
    gawk wget git diffstat unzip texinfo \
    gcc build-essential chrpath \
    socat cpio python3 python3-pip \
    python3-pexpect xz-utils debianutils \
    iputils-ping python3-git python3-jinja2 \
    libegl1-mesa libsdl1.2-dev python3-subunit \
    mesa-common-dev zstd liblz4-tool \
    file locales libacl1 \
    # Several other packages to run
    iproute2 \
    tmux \
    # Clean image
    && apt -y autoremove \
    && rm -rf /var/lib/apt/lists/* \
    # Set the locales correct
    && locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    # Install python packages for devtool to be able to parse python packages
    && python3 -m pip install tomli \
    # and install kas
    kas

# Create a user
ENV USER_NAME yocto
ARG host_uid=1000
ARG host_gid=1000

RUN echo "${USER_NAME} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/${USER_NAME} && \
    chmod 0440 /etc/sudoers.d/${USER_NAME} \
    # The running container writes all the build artefacts to a host directory (outside the container).
    # The container can only write files to host directories, if it uses the same user ID and
    # group ID owning the host directories. The host_uid and group_uid are passed to the docker build
    # command with the --build-arg option. By default, they are both 1000. The docker image creates
    # a group with host_gid and a user with host_uid and adds the user to the group.
    && groupadd -g $host_gid $USER_NAME && useradd -g $host_gid -m -s /bin/bash -u $host_uid $USER_NAME \
    && echo ${USER_NAME}:${USER_NAME} | chpasswd

USER ${USER_NAME}
# Install the dependency for linting
RUN python3 -m pip install --user oelint-adv

WORKDIR /