FROM ubuntu:24.04

RUN rm /bin/sh && ln -s bash /bin/sh

# Set environment variables for locale
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8

# Install all yocto dependencies
RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    locales \
    && rm -rf /var/lib/apt/lists/* \
# Set the locales correct
    && locale-gen en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    build-essential \
    chrpath \
    cpio \
    debianutils \
    diffstat \
    file \
    gawk \
    gcc \
    git \
    iputils-ping \
    libacl1 \
    liblz4-tool \
    locales \
    python3 \
    python3-git \
    python3-jinja2 \
    python3-pexpect \
    python3-pip \
    python3-subunit \
    socat \
    texinfo \
    unzip \
    wget \
    xz-utils \
    zstd

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    libsdl1.2-dev \
    mesa-common-dev \
    iproute2 \
    tmux

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    parted \
    mtools

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    gcc-multilib \
    git-core \
    xterm

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    device-tree-compiler

RUN apt update && \
    DEBIAN_FRONTEND=noninteractive apt install -y \
    npm && \
    npm install -g http-server

RUN apt -y autoremove && \
    rm -rf /var/lib/apt/lists/*

# Install python packages for devtool to be able to parse python packages
RUN pip3 install --break-system-packages tomli \
    # and install kas
    kas

ARG kvm_gid=108

# Create the kvm group with the specified GID and add the ubuntu user to it
RUN groupadd -g ${kvm_gid} kvm && \
    usermod -aG kvm ubuntu

USER ubuntu

# Install the dependency for linting
RUN pip3 install --break-system-packages --user oelint-adv

WORKDIR /