# THIS IS PREINSTALLED CONFIGURATION.YAML
# As a basis the default generated HA version is used and items are appended if the need to be activated

# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
